[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false
	#
	#How dynamic assets are generated. If cached the cache will regenerate once any mod or pack changes
	#- NEVER: This mod will never attempt to generate the cache folder. The assets will be put in memory
	#- RUN_ONCE: Will generate once in memory every time you launched. This mean it is only one time, that's it.
	#- CACHED: create a CACHE folder via .minecraft/dynamic-data-pack-cache
	#- CACHED_ZIPPED: create a ZIP folder via .minecraft/dynamic-data-pack-cache
	#- ALWAYS: regenerate on every time you load the world. /reload is included, too
	#Allowed Values: NEVER, RUN_ONCE, CACHED, CACHED_ZIPPED, ALWAYS
	server_assets_generation_mode = "CACHED_ZIPPED"
	#Allow the item_search or searchBar to be visible.
	tab_item_search = true

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false
