[general]
	#
	#How dynamic assets are generated. If cached the cache will regenerate once any mod or pack changes
	#- NEVER: This mod will never attempt to generate the cache folder. The assets will be put in memory
	#- RUN_ONCE: Will generate once in memory every time you launched. This mean it is only one time, that's it.
	#- CACHED: create a CACHE folder via .minecraft/dynamic-resource-pack-cache
	#- CACHED_ZIPPED: create a ZIP folder via .minecraft/dynamic-resource-pack-cache
	#- ALWAYS: regenerate on every time you launched Minecraft. Reload (F3 + T) is included, too
	#Allowed Values: NEVER, RUN_ONCE, CACHED, CACHED_ZIPPED, ALWAYS
	dynamic_assets_generation_mode = "CACHED_ZIPPED"
