#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

		[types.wood_type.arts_and_crafts]
			cork = true

		[types.wood_type.nomansland]
			pine = true
			maple = true
			walnut = true
			willow = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.enderscape]
			veiled = true
			celestial = true
			murublight = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.artistry]
			aspen = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.leaves_type.arts_and_crafts]
			cork = true

		[types.leaves_type.nomansland]
			yellow_birch = true
			autumnal_oak = true
			pale_cherry = true
			frosted = true
			pine = true
			maple = true
			red_maple = true
			walnut = true
			willow = true
			apple_fruit = true
			pear_fruit = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.aether]
			golden_oak = true
			holiday = true
			decorated_holiday = true
			crystal = true
			crystal_fruit = true
			skyroot = true

		[types.leaves_type.deep_aether]
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.artistry]
			aspen = true

		[types.leaves_type.no_mans_delight]
			orange_fruit = true

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.stone_type.arts_and_crafts]
			gypsum = true
			white_chalk = true
			soapstone = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.enderscape]
			mirestone = true
			veradite = true
			kurodite = true

		[types.stone_type.dndecor]
			cut_stone = true

		[types.stone_type.deep_aether]
			clorite = true
			raw_clorite = true
			aseterite = true

		[types.stone_type.ars_nouveau]
			sourcestone = true

		[types.stone_type.aether]
			holystone = true

		[types.stone_type.nomansland]
			silt = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

		[types.cake.nomansland]
			fruit_cake = true

		[types.mud_type.deep_aether]
			aether_mud = true

#Disables specific entries
[entries]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			couch = true
			shelf = true
			nightstand = true
			table = true
			chair = true
			drawer = true
			cupboard = true
			pillar_trim = true
			dining_bench = true
			side_table = true
			bench = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.woodworks]
			trapped_chest = true
			boards = true
			chest = true
			beehive = true
			bookshelf = true
			chiseled_bookshelf = true
			ladder = true

		[entries.wood_type.valhelsia_structures]
			bundled_stripped_posts = true
			stripped_post = true
			cut_post = true
			bundled_posts = true
			post = true
			cut_stripped_post = true

		[entries.wood_type.valhelsia_furniture]
			table = true
			stool = true
			hay_chair = true
			chair = true
			desk_drawer = true
			desk = true

		[entries.leaves_type.woodworks]
			leaf_pile = true

		[entries.stone_type.create]
			small_brick_wall = true
			cut_wall = true
			small_bricks = true
			cut_brick_slab = true
			polished_cut_slab = true
			small_brick_stairs = true
			cut_bricks = true
			cut = true
			polished_cut = true
			small_brick_slab = true
			layered = true
			polished_cut_stairs = true
			cut_brick_wall = true
			pillar = true
			cut_stairs = true
			cut_brick_stairs = true
			polished_cut_wall = true
			cut_slab = true

		[entries.stone_type.handcrafted]
			corner_trim = true
			pillar_trim = true
